kubernetes-replicator:
  serviceAccount:
    create: true
    annotations: {}
    name:
    privileges:
      - apiGroups: ["", "apps", "extensions"]
        resources: ["secrets", "configmaps"]

  # -- Resource requests and limits for kubernetes-replicator
  # @default -- See `values.yaml`
  resources:
    limits:
      cpu: "1"
      memory: "32Mi"
    requests:
      cpu: "1m"
      memory: "14Mi"
