{{- if .Values.config.ldap.kerberosConfig }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: "gafaelfawr-config-kerberos"
  labels:
    {{- include "gafaelfawr.labels" . | nindent 4 }}
data:
  krb5.conf: {{ .Values.config.ldap.kerberosConfig | quote }}
{{- end }}
