repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-merge-conflict
      - id: check-toml
      - id: trailing-whitespace

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.32.0
    hooks:
      - id: yamllint
        args:
          - -c=.yamllint.yml

  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.23.3
    hooks:
      - id: check-jsonschema
        files: "^applications/.*/secrets(-[^./-]+)?\\.yaml"
        args: ["--schemafile", "docs/extras/schemas/secrets.json"]
      - id: check-metaschema
        files: "^docs/extras/schemas/.*\\.json"

  - repo: https://github.com/norwoodj/helm-docs
    rev: v1.11.1
    hooks:
      - id: helm-docs
        args:
          - --chart-search-root=.
          # The `./` makes it relative to the chart-search-root set above
          - --template-files=./helm-docs.md.gotmpl
          - --document-dependency-values=true

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.280
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]

  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black

  - repo: https://github.com/adamchainz/blacken-docs
    rev: 1.15.0
    hooks:
      - id: blacken-docs
        additional_dependencies: [black==23.7.0]
