orders:
  commission:
    - name: initcommission
      image: lsstsqre/inituserhome
      securityContext:
        runAsUser: 0
        runAsNonRootUser: false
      volumeMounts:
        - mountPath: /homedirs
          name: homedirs
  volumes:
    - name: homedirs
      nfs:
        server: 10.72.0.168
        path: /jhome
