name: "ccin2p3"
fqdn: "data-dev.lsst.eu"
appOfAppsName: "science-platform"
vaultPathPrefix: "secret/k8s_operator/rsp-cc"

applications:
  datalinker: true
  nublado: true
  portal: true
  postgres: true
  semaphore: true
  squareone: true
  tap: true
