name: "rsptest"
fqdn: "rsp-test.lsst.ac.uk"
appOfAppsName: "science-platform"
vaultUrl: "https://vault.lsst.ac.uk"
vaultPathPrefix: secret/k8s_operator/rsptest_test

applications:
  mobu: true
  nublado: true
  portal: true
  postgres: true
  squareone: true
  tap: true
