prompt-proto-service:

  podAnnotations:
    # Expect to need roughly n_detector × request_latency / survey_cadence pods
    # For a 30 s ComCam survey with 500 s latency, this is 150
    autoscaling.knative.dev/max-scale: "150"
    autoscaling.knative.dev/target-utilization-percentage: "100"
    # Update this field if using latest or static image tag in dev
    revision: "1"

  worker:
    # Embargo rack allows fast cleanup.
    grace_period: 20

  image:
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: 4.2.0

  instrument:
    pipelines:
      main: >-
        (survey="BLOCK-297")=[${PROMPT_PROCESSING_DIR}/pipelines/LSSTComCamSim/ApPipe.yaml,
        ${PROMPT_PROCESSING_DIR}/pipelines/LSSTComCamSim/SingleFrame.yaml,
        ${PROMPT_PROCESSING_DIR}/pipelines/LSSTComCamSim/Isr.yaml]
        (survey="")=[]
      preprocessing: >-
        (survey="BLOCK-297")=[]
        (survey="")=[]
    calibRepo: s3://rubin-summit-users

  s3:
    imageBucket: rubin-summit
    endpointUrl: https://sdfembs3.sdf.slac.stanford.edu

  imageNotifications:
    kafkaClusterAddress: prompt-processing-2-kafka-bootstrap.kafka:9092
    topic: rubin-summit-notification

  apdb:
    config: s3://rubin-summit-users/apdb_config/cassandra/pp_apdb_lsstcomcamsim_or4.py

  alerts:
    topic: alerts-simulated

  sasquatch:
    endpointUrl: https://usdf-rsp-dev.slac.stanford.edu/sasquatch-rest-proxy
    namespace: lsst.prompt.prod
    auth_env: false

  logLevel: timer.lsst.activator=DEBUG lsst.diaPipe=VERBOSE lsst.rbClassify=VERBOSE

  knative:
    memoryLimit: "16Gi"

  fullnameOverride: "prompt-proto-service-lsstcomcamsim"
