vault-secrets-operator:
  environmentVars:
    - name: "VAULT_TOKEN"
      valueFrom:
        secretKeyRef:
          name: "vault-secrets-operator"
          key: "VAULT_TOKEN"
    - name: "VAULT_TOKEN_LEASE_DURATION"
      value: "31536000"
  vault:
    authMethod: "token"
