---
apiVersion: v1
kind: ConfigMap
metadata:
  name: butler
data:
# WARNING! The files in this configmap are served publicly on the internet via unauthenticated HTTP.
# DO NOT PUT ANY SENSITIVE INFORMATION IN THESE FILES.
{{- if .Values.config.dp02PostgresUri }}
  dp02.yaml: |
    datastore:
      cls: lsst.daf.butler.datastores.chainedDatastore.ChainedDatastore
      datastore_constraints:
        # One entry per datastore in datastores section
        # Use empty `-` if no constraint override required
        - constraints:
            reject:
              - all
        - constraints:
            accept:
              - all
      datastores:
        - datastore:
            name: FileDatastore@s3://butler-us-central1-panda-dev/dc2
            cls: lsst.daf.butler.datastores.fileDatastore.FileDatastore
            root: s3://butler-us-central1-panda-dev/dc2
        - datastore:
            name: FileDatastore@s3://butler-us-central1-dp02-user
            cls: lsst.daf.butler.datastores.fileDatastore.FileDatastore
            root: s3://butler-us-central1-dp02-user/
            records:
              table: user_datastore_records
    registry:
      db: {{ .Values.config.dp02PostgresUri }}
      managers:
        collections: lsst.daf.butler.registry.collections.synthIntKey.SynthIntKeyCollectionManager
        datasets: lsst.daf.butler.registry.datasets.byDimensions.ByDimensionsDatasetRecordStorageManagerUUID
        attributes: lsst.daf.butler.registry.attributes.DefaultButlerAttributeManager
        datastores: lsst.daf.butler.registry.bridge.monolithic.MonolithicDatastoreRegistryBridgeManager
        dimensions: lsst.daf.butler.registry.dimensions.static.StaticDimensionRecordStorageManager
        opaque: lsst.daf.butler.registry.opaque.ByNameOpaqueTableStorageManager
      namespace: dc2_20210215
  # Repository index for END USERS defining aliases for Butler configurations.
  # This is NOT the configuration used internally for Butler server itself.
  # It is also NOT the configuration that should be used by Phalanx services
  # connecting to the Butler server.
  #
  # We provide both DirectButler and RemoteButler versions of dp02 because some
  # users rely on functionality not yet available via RemoteButler.  The default is currently
  # DirectButler because the Community Science team has not had the opportunity to test RemoteButler,
  # and RemoteButler is not available in the current "recommended" RSP image.
  idf-repositories.yaml: |
    dp02: {{ .Values.global.baseUrl }}{{ .Values.config.pathPrefix }}/configs/dp02.yaml
    dp02-direct: {{ .Values.global.baseUrl }}{{ .Values.config.pathPrefix }}/configs/dp02.yaml
    dp02-remote: {{ .Values.global.baseUrl }}{{ .Values.config.pathPrefix }}/repo/dp02/butler.yaml
{{- end }}
