{{- if (or .Values.config.serviceAccount .Values.cloudsql.enabled) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "vo-cutouts"
  labels:
    {{- include "vo-cutouts.labels" . | nindent 4 }}
  annotations:
    iam.gke.io/gcp-service-account: {{ required "config.serviceAccount must be set to a valid Google service account" .Values.config.serviceAccount | quote }}
{{- end }}
