auxtel-ess201:
  # -- Enable the ESS:201 CSC
  enabled: false

auxtel-ess201-sim:
  # -- Enable the ESS:201 simulator CSC
  enabled: false

auxtel-ess202:
  # -- Enable the ESS:202 CSC
  enabled: false

auxtel-ess202-sim:
  # -- Enable the ESS:202 simulator CSC
  enabled: false

auxtel-ess203:
  # -- Enable the ESS:203 CSC
  enabled: false

auxtel-ess203-sim:
  # -- Enable the ESS:203 simulator CSC
  enabled: false

auxtel-ess204:
  # -- Enable the ESS:204 CSC
  enabled: false

auxtel-ess204-sim:
  # -- Enable the ESS:204 simulator CSC
  enabled: false

auxtel-ess205:
  # -- Enable the ESS:205 CSC
  enabled: false

auxtel-ess205-sim:
  # -- Enable the ESS:205 simulator CSC
  enabled: false

calibhill-ess301:
  # -- Enable the ESS:301 CSC
  enabled: false

calibhill-ess301-sim:
  # -- Enable the ESS:301 simulator CSC
  enabled: false

dimm1:
  # -- Enable the DIMM:1 CSC
  enabled: false

dimm1-sim:
  # -- Enable the DIMM:1 simulator CSC
  enabled: false

dimm2:
  # -- Enable the DIMM:2 CSC
  enabled: false

dimm2-sim:
  # -- Enable the DIMM:2 simulator CSC
  enabled: false

dsm1:
  # -- Enable the DSM:1 CSC
  enabled: false

dsm1-sim:
  # -- Enable the DSM:1 simulator CSC
  enabled: false

dsm2:
  # -- Enable the DSM:2 CSC
  enabled: false

dsm2-sim:
  # -- Enable the DSM:2 simulator CSC
  enabled: false

epm1:
  # -- Enable the EPM:1 CSC
  enabled: false

epm1-sim:
  # -- Enable the EPM:1 simulator CSC
  enabled: false

m2-ess106:
  # -- Enable the ESS:106 CSC
  enabled: false

m2-ess106-sim:
  # -- Enable the ESS:106 simulator CSC
  enabled: false

mtdome-ess101:
  # -- Enable the ESS:101 CSC
  enabled: false

mtdome-ess101-sim:
  # -- Enable the ESS:101 simulator CSC
  enabled: false

mtdome-ess102:
  # -- Enable the ESS:102 CSC
  enabled: false

mtdome-ess102-sim:
  # -- Enable the ESS:102 simulator CSC
  enabled: false

mtdome-ess103:
  # -- Enable the ESS:103 CSC
  enabled: false

mtdome-ess103-sim:
  # -- Enable the ESS:103 simulator CSC
  enabled: false

mtdome-ess107:
  # -- Enable the ESS:107 CSC
  enabled: false

mtdome-ess107-sim:
  # -- Enable the ESS:107 simulator CSC
  enabled: false

mtdome-ess108:
  # -- Enable the ESS:108 CSC
  enabled: false

mtdome-ess108-sim:
  # -- Enable the ESS:108 simulator CSC
  enabled: false

tma-ess001:
  # -- Enable the ESS:1 CSC
  enabled: false

tma-ess001-sim:
  # -- Enable the ESS:1 simulator CSC
  enabled: false

tma-ess104:
  # -- Enable the ESS:104 CSC
  enabled: false

tma-ess104-sim:
  # -- Enable the ESS:104 simulator CSC
  enabled: false

tma-ess105:
  # -- Enable the ESS:105 CSC
  enabled: false

tma-ess105-sim:
  # -- Enable the ESS:105 simulator CSC
  enabled: false

# The following will be set by parameters injected by Argo CD and should not
# be set in the individual environment values files.
global:
  # -- Base URL for the environment
  # @default -- Set by Argo CD
  baseUrl: ""

  # -- Host name for ingress
  # @default -- Set by Argo CD
  host: ""

  # -- Base path for Vault secrets
  # @default -- Set by Argo CD
  vaultSecretsPath: ""

  controlSystem:
    # -- Application namespace for the control system deployment
    # @default -- Set by ArgoCD
    appNamespace: ""

    # -- Image tag for the control system deployment
    # @default -- Set by ArgoCD
    imageTag: ""

    # -- Site tag for the control system deployment
    # @default -- Set by ArgoCD
    siteTag: ""

    # -- Topic name tag for the control system deployment
    # @default -- Set by ArgoCD
    topicName: ""

    # -- Kafka broker address for the control system deployment
    # @default -- Set by ArgoCD
    kafkaBrokerAddress: ""

    # -- Kafka topic replication factor for control system topics
    # @default -- Set by ArgoCD
    kafkaTopicReplicationFactor: ""

    # -- Schema registry URL for the control system deployment
    # @default -- Set by ArgoCD
    schemaRegistryUrl: ""

    # -- S3 endpoint (LFA) for the control system deployment
    # @default -- Set by ArgoCD
    s3EndpointUrl: ""
