{{- if .Values.config.githubRefreshApp -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mobu.fullname" . }}-github-refresh-app
  labels:
    {{- include "mobu.labels" . | nindent 4 }}
data:
  github-refresh-app.yaml: |
    {{- toYaml .Values.config.githubRefreshApp | nindent 4 }}
{{- end }}
