{{- if .Values.config.githubCiApp -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mobu.fullname" . }}-github-ci-app
  labels:
    {{- include "mobu.labels" . | nindent 4 }}
data:
  github-ci-app.yaml: |
    {{- toYaml .Values.config.githubCiApp | nindent 4 }}
{{- end }}
