cadc-tap:
  tapSchema:
    image:
      repository: "lsstsqre/tap-schema-idfint-tap"

  config:
    qserv:
      host: "qserv-int.slac.stanford.edu:4090"
      jdbcParams: "?enabledTLSProtocols=TLSv1.2"
      passwordEnabled: true
